# Generated by Django 4.1 on 2022-08-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ispb", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.IntegerField(blank=True, null=True)),
                ("fullName", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "db_table": "tb_banks",
            },
        ),
    ]
